/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package epsilongtmyon;

import javax.servlet.HttpConstraintElement;
import javax.servlet.ServletContext;
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.ServletRegistration.Dynamic;
import javax.servlet.ServletSecurityElement;
import javax.servlet.annotation.ServletSecurity.TransportGuarantee;
import javax.servlet.annotation.WebListener;

import epsilongtmyon.app.common.filters.EncodingFilter;
import epsilongtmyon.app.pages.sandbox01.Sandbox01Servlet;

@WebListener
public class App implements ServletContextListener {

	@Override
	public void contextInitialized(ServletContextEvent sce) {
		ServletContext sc = sce.getServletContext();

		Dynamic sandbox01ServletDynamic = sc.addServlet("sandbox01", Sandbox01Servlet.class);
		sandbox01ServletDynamic.addMapping("/sandbox01/*");

		javax.servlet.FilterRegistration.Dynamic encodingFilterDynamic = sc.addFilter("encoding", EncodingFilter.class);
		encodingFilterDynamic.addMappingForUrlPatterns(null, false, "/*");

		// web.xmlのsecurity-constraint部分をコードで設定することができる
		// Servlet単位でありURLで直接は紐づけれないのかな？？
		HttpConstraintElement httpConstraintElement = new HttpConstraintElement(TransportGuarantee.NONE, "role01");
		ServletSecurityElement securityElem = new ServletSecurityElement(httpConstraintElement);
		sandbox01ServletDynamic.setServletSecurity(securityElem);
	}

}
