/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package epsilongtmyon;

import org.junit.jupiter.api.Test;

import epsilongtmyon.support.util.ResourceUtil;

class AppTest {
	@Test
	void appHasAGreeting() {
		String schema = ResourceUtil.getResourceAsString("schema.sql");
		
		System.out.println(schema);
	}
}
