services:
  # https://github.com/minio/minio
  # https://hub.docker.com/r/minio/minio/tags
  minio:
    image: "minio/minio:RELEASE.2025-07-23T15-54-02Z"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - type: volume
        source: minio-volume
        target: /data
    command: server /data --console-address ":9001"

volumes:
  minio-volume:
