/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package epsilongtmyon;

import java.io.IOException;
import java.util.Date;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;

public class App {
	
	private static Logger logger = LoggerFactory.getLogger(App.class);
	
    public static void main(String[] args) {
    	MDC.put("myXxx", new Date().toString());
    	
    	logger.info("あいうえお");
    	logger.info("プレースホルダー:{}", "XXX");
    	logger.atWarn()
    		.addKeyValue("aaa", "あああ")
    		.addKeyValue("bbb", "いいい")
    		.log("あああああああ");
    	
    	
    	logger.error("例外", new Exception("れいがい", new IOException("IOです。")));
    }
}
