import net.ltgt.gradle.errorprone.errorprone
import net.ltgt.gradle.errorprone.CheckSeverity;
import org.gradle.api.tasks.compile.JavaCompile;

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    // errorprone からnullaway -> jspecifyを使うので
    id("net.ltgt.errorprone") version "5.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    implementation("org.jspecify:jspecify:1.0.0")
    
    // Source: https://mvnrepository.com/artifact/org.springframework/spring-core
	implementation("org.springframework:spring-core:7.0.6")
    
    // nullawayを使うため
  	errorprone("com.uber.nullaway:nullaway:0.13.1")
  	errorprone("com.google.errorprone:error_prone_core:2.48.0")
    
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// 設定はこの辺りを参考
// https://www.docswell.com/s/WN_Tech-PR/ZM6PPE-2025-11-15-125730#p83
tasks.withType<JavaCompile>().configureEach {
    options.errorprone {
        // nullawayのチェックを無効化
        disableAllChecks = true
        // NullAwayのチェックをエラー扱い
        check("NullAway", CheckSeverity.ERROR)
        // チェック対象のパッケージ
        option("NullAway:AnnotatedPackages", "epsilongtmyon")
    }

    // Include to disable NullAway on test code
    if (name.lowercase().contains("test")) {
        options.errorprone {
            disable("NullAway")
        }
    }
}


