
insert into MY_TABLE (STRING_COL, BIGINT_COL, INTEGER_COL, BIGDECIMAL_COL, DATE_COL, TIMESTAMP_COL, CREATED_AT, UPDATED_AT)
  values (null, null, null, null, null, null, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);